indentation_width: 4
cyclomatic_complexity:
  warning: 1
file_length:
  error: 1000
function_body_length: 
  warning: 35
function_parameter_count: 5
type_body_length: 300

disabled_rules:
  - valid_docs
  - identifier_name

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

force_cast: warning # implicitly
force_try:
  severity: error # explicitly
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - GildedRoseTests

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
